### ISSUE TITLE
Reset `-webkit-font-smoothing`

### ISSUE THREAD

**Issue by nanxstats** [elong0527/r4csr#109]
In the default Bootswatch theme "cosmo" that Quarto book uses, there is this rule:

```css
body {
  -webkit-font-smoothing: antialiased;
}
```

This rule might not be too useful in web typography today (search "stop fixing font smoothing" and see the opinions).

So I would propose to reset it to:

```css
body { 
  -webkit-font-smoothing: auto; 
}
```

I will send a PR.
